### ISSUE TITLE
Gremlin Server failing at creating 'sevenbridges' Graph every time the database boots up.

### ISSUE THREAD

**Issue by vsantosu** [TruenoDB/trueno#3]
When there is no data and the database boots up, the gremlin server tries to create the 'sevenbridges' graph. If present it will update each edge and vertices, if does not exist it it will fail with the following error.

`info: ex_create invoked ftr=[val=sevenbridges, ftr=AND, prop=label, type=term], jobId=, , , , id=sevenbridges, label=sevenbridges, type=g, graph=sevenbridges, mask=true
info: ex_persist. [ e ] Failure!
info: ex_persist. [ e ] Failure!
info: ex_persist. [ v ] Failure!
info: ex_persist. [ v ] Failure!
info: ex_persist. [ v ] Failure!
info: ex_persist. [ v ] Failure!
info: ex_persist. [ e ] Failure!
info: ex_persist. [ e ] Failure!
info: ex_persist. [ e ] Failure!
info: ex_persist. [ e ] Failure!
info: ex_persist. [ e ] Failure!
info: Cassandra instance connected on  [ 'EVA1' ] : 0=9042
{ Error: Keyspace sevenbridges does not exist
    at ResponseError.DriverError (/Users/victor/Desktop/trueno/node_modules/cassandra-driver/lib/errors.js:14:19)
    at new ResponseError (/Users/victor/Desktop/trueno/node_modules/cassandra-driver/lib/errors.js:51:24)
    at FrameReader.readError (/Users/victor/Desktop/trueno/node_modules/cassandra-driver/lib/readers.js:316:13)
    at Parser.parseBody (/Users/victor/Desktop/trueno/node_modules/cassandra-driver/lib/streams.js:194:66)
    at Parser._transform (/Users/victor/Desktop/trueno/node_modules/cassandra-driver/lib/streams.js:137:10)
    at Parser.Transform._read (_stream_transform.js:167:10)
    at Parser.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:306:12)
    at writeOrBuffer (_stream_writable.js:292:5)
    at Parser.Writable.write (_stream_writable.js:220:11)
    at Protocol.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Protocol.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:172:18)
    at Protocol.Readable.push (_stream_readable.js:130:10)
    at Protocol.Transform.push (_stream_transform.js:128:32)
  name: 'ResponseError',
  stack: 'Error: Keyspace sevenbridges does not exist\n    at ResponseError.DriverError (/Users/victor/Desktop/trueno/node_modules/cassandra-driver/lib/errors.js:14:19)\n    at new ResponseError (/Users/victor/Desktop/trueno/node_modules/cassandra-driver/lib/errors.js:51:24)\n    at FrameReader.readError (/Users/victor/Desktop/trueno/node_modules/cassandra-driver/lib/readers.js:316:13)\n    at Parser.parseBody (/Users/victor/Desktop/trueno/node_modules/cassandra-driver/lib/streams.js:194:66)\n    at Parser._transform (/Users/victor/Desktop/trueno/node_modules/cassandra-driver/lib/streams.js:137:10)\n    at Parser.Transform._read (_stream_transform.js:167:10)\n    at Parser.Transform._write (_stream_transform.js:155:12)\n    at doWrite (_stream_writable.js:306:12)\n    at writeOrBuffer (_stream_writable.js:292:5)\n    at Parser.Writable.write (_stream_writable.js:220:11)\n    at Protocol.ondata (_stream_readable.js:555:20)\n    at emitOne (events.js:96:13)\n    at Protocol.emit (events.js:188:7)\n    at readableAddChunk (_stream_readable.js:172:18)\n    at Protocol.Readable.push (_stream_readable.js:130:10)\n    at Protocol.Transform.push (_stream_transform.js:128:32)',
  message: 'Keyspace sevenbridges does not exist',
  info: 'Represents an error message from the server',
  code: 8704,
  coordinator: '192.168.1.45:9042',
  query: 'UPDATE sevenbridges.VERTICES SET partition = 0,prop = { \'name\' : (\'string\', \'A\') },comp = {},meta = {} WHERE ID = 1;' }
{ Error: Keyspace sevenbridges does not exist
    at ResponseError.DriverError (/Users/victor/Desktop/trueno/node_modules/cassandra-driver/lib/errors.js:14:19)
    at new ResponseError (/Users/victor/Desktop/trueno/node_modules/cassandra-driver/lib/errors.js:51:24)
    at FrameReader.readError (/Users/victor/Desktop/trueno/node_modules/cassandra-driver/lib/readers.js:316:13)
    at Parser.parseBody (/Users/victor/Desktop/trueno/node_modules/cassandra-driver/lib/streams.js:194:66)
    at Parser._transform (/Users/victor/Desktop/trueno/node_modules/cassandra-driver/lib/streams.js:137:10)
    at Parser.Transform._read (_stream_transform.js:167:10)
    at Parser.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:306:12)
    at writeOrBuffer (_stream_writable.js:292:5)
    at Parser.Writable.write (_stream_writable.js:220:11)
    at Protocol.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Protocol.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:172:18)
    at Protocol.Readable.push (_stream_readable.js:130:10)
    at Protocol.Transform.push (_stream_transform.js:128:32)
`

We need to fix this by first checking if the graph exist(g.fetch('g', filter with label=sevenbridges').

- If exist, do nothing.
- If does not exist, create it and do a **batch insert** not one by one.

The problem is that is not doing the procedure asynchronous, i.e. is trying to insert vertices and edges before the graph is created, this needs to be changed to prevent this error.

**Comment by ebarsallo** [comment]
Solved on: [0aa66c527d5ca04dcd1ae68f1b30045f61cd6dfd](https://github.com/TruenoDB/trueno-gremlin/commit/0aa66c527d5ca04dcd1ae68f1b30045f61cd6dfd)
Asynchronous support was added for "open" operation. In this case, the inserts are only donde after the open operation finish (either create the corresponding structures or just fetch the graph).

**Comment by vsantosu** [comment]
Perfect!!
